spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: Naver
            client-id: UFGOw6CnDfjpewOTiGT4
            client-secret: WMg2FL_TR1
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, mobile

          kakao:
            client-name: kakao
            client-id: b7407fed37c117dbed7c5158fbe0d8d0
            client-secret: adDDoZRH9aDSE05rqSZ3qkSxbtV0bTiJ
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname, profile_image

          google:
            client-name: google
            client-id: 376849172025-ull8317cbum5dbc0nm38cc356qr2h8jb.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: email, profile

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account